FROM postgres:15

# Define the directory where PostgreSQL stores its data
ENV PGDATA=/var/lib/postgresql/data/pgdata

# Set appropriate permissions for the initialization directory
RUN chmod -R 755 /docker-entrypoint-initdb.d

# Expose PostgreSQL’s default port
EXPOSE 5432