dbt_project:
  target: dev
  outputs:

    bigquery_dbt:
      type: bigquery
      method: service-account
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      keyfile: credentials/keys.json
      threads: 1
      timeout_seconds: 300
      job_retries: 1
      location: US
      priority: interactive

    redshift_dbt:
      type: redshift
      host: "{{ env_var('REDSHIFT_HOST') }}"
      port: 5439
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      dbname: "{{ env_var('REDSHIFT_DB') }}"
      schema: "{{ env_var('REDSHIFT_SCHEMA') }}"
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      sslmode: prefer